---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-server
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: ubuntu-server
    spec:
      domain:
        cpu:
          cores: 4
        memory:
          guest: 8Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinit
              disk:
                bus: virtio
          interfaces:
            - name: lan
              bridge: {}
      networks:
        - name: lan
          multus:
            networkName: network/vm
      volumes:
        - name: rootdisk
          dataVolume:
            name: ubuntu-server
        - name: cloudinit
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: ubuntu-server
              manage_etc_hosts: true
              users:
                - name: admin
                  groups: [adm, sudo]
                  shell: /bin/bash
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  ssh_authorized_keys:
                    - "${SECRET_SSH_PUBLIC_KEY}"
              package_update: true
              packages:
                - qemu-guest-agent
              runcmd:
                - systemctl enable --now qemu-guest-agent
