---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kubevirt.io/virtualmachine_v1.json
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-server
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: ubuntu-server
      annotations:
        k8s.v1.cni.cncf.io/networks: |-
          [{
            "name": "vm",
            "namespace": "network",
            "ips": ["192.168.57.10/24"],
            "mac": "52:54:00:57:00:10"
          }]
    spec:
      domain:
        cpu:
          cores: 1
        memory:
          guest: 1Gi
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinit
              disk:
                bus: virtio
          interfaces:
            - name: lan
              bridge: {}
      networks:
        - name: lan
          multus:
            networkName: network/vm
      volumes:
        - name: rootdisk
          dataVolume:
            name: ubuntu-server
        - name: cloudinit
          cloudInitNoCloud:
            userData: |
              #cloud-config
              hostname: ubuntu-server
              manage_etc_hosts: true
              users:
                - name: admin
                  groups: [adm, sudo]
                  shell: /bin/bash
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  ssh_authorized_keys:
                    - "${SECRET_SSH_PUBLIC_KEY}"
              package_update: true
              packages:
                - qemu-guest-agent
              runcmd:
                - systemctl enable --now qemu-guest-agent
            networkData: |
              version: 2
              ethernets:
                enp1s0:
                  addresses:
                    - 192.168.57.10/24
                  routes:
                    - to: default
                      via: 192.168.57.1
                  nameservers:
                    addresses:
                      - 10.0.6.1
