---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-server
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: ubuntu-server
      annotations:
        kubevirt.io/allow-pod-bridge-network-live-migration: "true"
        k8s.v1.cni.cncf.io/networks: |-
          [{
            "name": "vm-macvtap",
            "namespace": "network",
            "mac": "52:54:00:57:00:10"
          }]
    spec:
      evictionStrategy: LiveMigrate
      domain:
        cpu:
          cores: 1
        resources:
          requests:
            memory: 1G
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: lan
              binding:
                name: macvtap
      networks:
        - name: lan
          multus:
            networkName: network/vm-macvtap
      volumes:
        - name: rootdisk
          dataVolume:
            name: ubuntu-server-pvc
        - name: cloudinitdisk
          cloudInitNoCloud:
            networkData: |
              network:
                version: 1
                config:
                  - type: physical
                    name: enp1s0
                    subnets:
                      - type: static
                        address: 192.168.57.10/24
                        gateway: 192.168.57.1
                        dns_nameservers:
                          - 10.0.6.1
            userData: |
              #cloud-config
              hostname: ubuntu-server
              manage_etc_hosts: true
              users:
                - name: admin
                  groups: [adm, sudo]
                  shell: /bin/bash
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  ssh_authorized_keys:
                    - "${SECRET_SSH_PUBLIC_KEY}"
              package_update: true
              packages:
                - qemu-guest-agent
              runcmd:
                - systemctl enable --now qemu-guest-agent
  dataVolumeTemplates:
    - metadata:
        name: ubuntu-server-pvc
      spec:
        storage:
          resources:
            requests:
              storage: 30Gi
          accessModes:
            - ReadWriteMany
          storageClassName: nfs-fast
        source:
          http:
            url: "https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img"
