---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres17
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.7-202601260808-system-bullseye
  primaryUpdateStrategy: unsupervised

  storage:
    size: 20Gi
    storageClass: openebs-hostpath

  superuserSecret:
    name: cloudnative-pg-secret

  enableSuperuserAccess: true

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: 256MB
      effective_cache_size: 512MB
      maintenance_work_mem: 128MB
      checkpoint_completion_target: "0.9"
      wal_buffers: 16MB
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: 4MB
      huge_pages: "off"
      min_wal_size: 1GB
      max_wal_size: 4GB

  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 2Gi

  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      destinationPath: s3://cnpg/
      endpointURL: http://garage.volsync-system.svc.cluster.local:3900
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secret
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: cloudnative-pg-secret
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: bzip2
        maxParallel: 2
      data:
        compression: bzip2
