---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

components:
  - ../../components/alerts
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./csi-driver-nfs/ks.yaml
  - ./kguardian/ks.yaml # Disabled until we move from proxmox nodes to bare metal
  - ./spegel/ks.yaml
