---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: b1-k3s01-secrets
spec:
  dependsOn:
    - name: onepassword
      namespace: external-secrets
  interval: 1h
  path: ./kubernetes/apps/kubevirt/virtualmachines/freepbx/b1-k3s01/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kubevirt
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: b1-k3s01
spec:
  dependsOn:
    - name: kubevirt
    - name: cdi
    - name: macvtap-cni
      namespace: network
    - name: b1-k3s01-secrets
  interval: 1h
  path: ./kubernetes/apps/kubevirt/virtualmachines/freepbx/b1-k3s01/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: b1-k3s01-vars
        kind: ConfigMap
      - name: b1-k3s01-secret
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kubevirt
  wait: false
