---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: penpot
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: penpot-secret
    template:
      engineVersion: v2
      data:
        PENPOT_SECRET_KEY: "{{ .PENPOT_SECRET_KEY }}"
        PENPOT_DATABASE_URI: "postgresql://postgres17-rw.database.svc.cluster.local:5432/{{ .PENPOT_POSTGRES_DB }}"
        INIT_POSTGRES_DBNAME: "{{ .PENPOT_POSTGRES_DB }}"
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_PORT: "5432"
        INIT_POSTGRES_USER: "{{ .PENPOT_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .PENPOT_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: penpot
    - extract:
        key: cloudnative-pg
