---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: penpot
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: penpot
  values:
    global:
      postgresqlEnabled: false
      redisEnabled: false
      valkeyEnabled: true

    config:
      publicUri: "https://penpot.00o.sh"
      flags: "enable-registration enable-login-with-password disable-email-verification"

      postgresql:
        host: postgres-rw.database.svc.cluster.local
        port: 5432
        username: penpot
        database: penpot
        existingSecret: penpot-secret
        secretKeys:
          usernameKey: INIT_POSTGRES_USER
          passwordKey: INIT_POSTGRES_PASS
          postgresqlUriKey: PENPOT_DATABASE_URI

      redis:
        host: penpot-valkey-primary
        port: 6379
        database: "0"

    backend:
      replicaCount: 1
      env:
        - name: PENPOT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: penpot-secret
              key: PENPOT_SECRET_KEY
      initContainers:
        - name: init-db
          image: ghcr.io/home-operations/postgres-init:18@sha256:3c54d39f19fdb82ed5b3f286450e4071133cc6025bd0e25856bc2c522f8fc030
          envFrom:
            - secretRef:
                name: penpot-secret

    frontend:
      replicaCount: 1

    exporter:
      replicaCount: 1

    persistence:
      assets:
        enabled: true
        existingClaim: penpot

    ingress:
      enabled: false
