---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: freepbx-b2-k3s01-database
  namespace: flux-system
spec:
  suspend: ${CLUSTER_TIER2_SUSPENDED}
  targetNamespace: database
  commonMetadata:
    labels:
      app.kubernetes.io/name: freepbx-b2-k3s01
  dependsOn:
    - name: mariadb-cluster
      namespace: database
    - name: onepassword
      namespace: external-secrets
  interval: 1h
  path: ./kubernetes/apps/voip/freepbx-b2-k3s01/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app freepbx-b2-k3s01
  namespace: flux-system
spec:
  suspend: ${CLUSTER_TIER2_SUSPENDED}
  targetNamespace: voip
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: freepbx-b2-k3s01-database
    - name: onepassword
      namespace: external-secrets
  interval: 1h
  path: ./kubernetes/apps/voip/freepbx-b2-k3s01/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
