---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: thelounge-oidc
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: thelounge
  oidc:
    provider:
      issuer: "https://auth.00o.sh/oauth2/openid/thelounge"
    clientID: "thelounge"
    clientSecret:
      name: thelounge-oidc-secret
    redirectURL: "https://thelounge.00o.sh/oauth2/callback"
    logoutPath: "/oauth2/sign_out"
