---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: librespeed
spec:
  chartRef:
    kind: OCIRepository
    name: librespeed
  interval: 1h
  values:
    controllers:
      speed-cf:
        strategy: RollingUpdate
        containers:
          app:
            image: &image
              repository: ghcr.io/librespeed/speedtest
              tag: 5.5.1
            env: &env
              MODE: backend
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /empty.php
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"], add: ["CHOWN"] }
            resources: &resources
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
      speed-direct:
        strategy: RollingUpdate
        containers:
          app:
            image: *image
            env: *env
            probes:
              liveness: *probes
              readiness: *probes
            securityContext: *securityContext
            resources: *resources
      speed-lan:
        strategy: RollingUpdate
        containers:
          app:
            image: *image
            env: *env
            probes:
              liveness: *probes
              readiness: *probes
            securityContext: *securityContext
            resources: *resources
      speed-frontend:
        strategy: RollingUpdate
        containers:
          app:
            image: *image
            env:
              MODE: frontend
            probes:
              liveness: &frontend-probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *frontend-probes
            securityContext: *securityContext
            resources: *resources
    service:
      speed-cf:
        controller: speed-cf
        ports:
          http:
            port: *port
      speed-direct:
        controller: speed-direct
        ports:
          http:
            port: *port
      speed-lan:
        type: LoadBalancer
        controller: speed-lan
        annotations:
          lbipam.cilium.io/ips: "10.0.6.16"
        ports:
          http:
            port: *port
      speed-frontend:
        controller: speed-frontend
        ports:
          http:
            port: *port
    configMaps:
      servers:
        data:
          servers.json: |-
            [
              {"name": "Cloudflare Proxied", "server": "//speed-cf.${SECRET_DOMAIN}/", "dlURL": "garbage.php", "ulURL": "empty.php", "pingURL": "empty.php", "getIpURL": "getIP.php"},
              {"name": "Direct", "server": "//speed-direct.${SECRET_DOMAIN}/", "dlURL": "garbage.php", "ulURL": "empty.php", "pingURL": "empty.php", "getIpURL": "getIP.php"},
              {"name": "LAN Direct", "server": "http://10.0.6.16:8080/", "dlURL": "garbage.php", "ulURL": "empty.php", "pingURL": "empty.php", "getIpURL": "getIP.php"}
            ]
    persistence:
      servers:
        type: configMap
        identifier: servers
        advancedMounts:
          speed-frontend:
            app:
              - path: /servers.json
                subPath: servers.json
    route:
      speed-cf:
        hostnames: ["speed-cf.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: speed-cf
                port: *port
      speed-direct:
        annotations:
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        hostnames: ["speed-direct.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: speed-direct
                port: *port
      speed-frontend:
        hostnames: ["speed.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: speed-frontend
                port: *port
