---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autobrr-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-identity
  target:
    name: autobrr-oidc-secret
    template:
      data:
        client-secret: "{{ .CLIENT_SECRET }}"
  data:
    - secretKey: CLIENT_SECRET
      remoteRef:
        key: autobrr-kanidm-oauth2-credentials
        property: CLIENT_SECRET
