---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: app-users
spec:
  kanidmRef:
    name: kanidm
  members:
    - ebrody
---
apiVersion: kaniop.rs/v1beta1
kind: KanidmGroup
metadata:
  name: penpot-users
spec:
  kanidmRef:
    name: kanidm
  members:
    - ebrody
