---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./externalsecret-s3.yaml
  - ./persons.yaml
  - ./groups.yaml
  - ./oauth2-dbgate.yaml
  - ./oauth2-forgejo.yaml
  - ./oauth2-kubevirt-manager.yaml
  - ./oauth2-opencost.yaml
  - ./oauth2-penpot.yaml
