---
apiVersion: kaniop.rs/v1beta1
kind: KanidmOAuth2Client
metadata:
  name: penpot
spec:
  kanidmRef:
    name: kanidm
  displayname: Penpot
  origin: "https://penpot.00o.sh"
  allowInsecureClientDisablePkce: true
  redirectUrl:
    - "https://penpot.00o.sh/api/auth/oidc/callback"
  scopeMap:
    - group: penpot-users
      scopes:
        - openid
        - email
        - profile
