---
apiVersion: kaniop.rs/v1beta1
kind: KanidmPersonAccount
metadata:
  name: ebrody
spec:
  kanidmRef:
    name: kanidm
  personAttributes:
    displayname: Eli Brody
    mail:
      - ebrody@bbb.consulting
---
apiVersion: kaniop.rs/v1beta1
kind: KanidmPersonAccount
metadata:
  name: herman
spec:
  kanidmRef:
    name: kanidm
  personAttributes:
    displayname: Herman Reisman
    mail:
      - herman@ambersecurity.net
