bindaddress = "[::]:8443"
ldapbindaddress = "[::]:3636"
trust_x_forward_for = true
db_path = "/data/kanidm.db"
tls_chain = "/certs/tls.crt"
tls_key = "/certs/tls.key"
domain = "auth.${SECRET_DOMAIN}"
origin = "https://auth.${SECRET_DOMAIN}"

[online_backup]
path = "/data/backups/"
schedule = "00 02 * * *"
