---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: b2-k3s01
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: b2-k3s01-secret
    template:
      data:
        FPBX_CF_TUNNEL_TOKEN: "{{ .FPBX_CF_TUNNEL_TOKEN }}"
  dataFrom:
    - extract:
        key: freepbx
