---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: freepbx-b2-k3s01
spec:
  chartRef:
    kind: OCIRepository
    name: freepbx-b2-k3s01
  interval: 1h
  values:
    controllers:
      freepbx-b2-k3s01:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/00o-sh/fpbx-docker
              tag: 17@sha256:af807d6280773a37584c35b4118f1c14056b4e457b7f739cb4e0b3d772dfb4c8
            env:
              DB_HOST: mariadb-primary.database.svc.cluster.local
              DB_PORT: "3306"
              DB_USER: freepbx_b2
              DB_NAME: b2_asterisk
              DB_CDR_NAME: b2_asteriskcdrdb
              DB_PASS:
                valueFrom:
                  secretKeyRef:
                    name: freepbx-b2-k3s01-secret
                    key: DB_PASS
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 80
                  initialDelaySeconds: 520
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 80
                  initialDelaySeconds: 520
                  periodSeconds: 10
                  timeoutSeconds: 10
                  failureThreshold: 5
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
                  - NET_RAW
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 2Gi

    defaultPodOptions:
      annotations:
        k8s.v1.cni.cncf.io/networks: |-
          [{
            "name": "voip",
            "namespace": "network",
            "ips": ["192.168.57.15/24"],
            "mac": "52:54:00:57:00:15"
          }]

    service:
      app:
        controller: freepbx-b2-k3s01
        annotations:
          external-dns.alpha.kubernetes.io/hostname: freepbx-b2-k3s01.00o.sh
          external-dns.alpha.kubernetes.io/target: 192.168.57.15
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: VoIP
          gethomepage.dev/name: FreePBX B2
          gethomepage.dev/icon: freepbx.png
          gethomepage.dev/description: Telephony Platform
          gethomepage.dev/href: "https://freepbx-b2-k3s01.00o.sh"
        ports:
          http:
            port: 80

    persistence:
      asterisk-etc:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: openebs-hostpath
        advancedMounts:
          freepbx-b2-k3s01:
            app:
              - path: /etc/asterisk
      asterisk-lib:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: openebs-hostpath
        advancedMounts:
          freepbx-b2-k3s01:
            app:
              - path: /var/lib/asterisk
      asterisk-spool:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: openebs-hostpath
        advancedMounts:
          freepbx-b2-k3s01:
            app:
              - path: /var/spool/asterisk
      asterisk-log:
        type: emptyDir
        advancedMounts:
          freepbx-b2-k3s01:
            app:
              - path: /var/log/asterisk
