---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: zitadel-secret
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: "{{ .ZITADEL_POSTGRES_DB }}"
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_PORT: "5432"
        INIT_POSTGRES_USER: "{{ .ZITADEL_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .ZITADEL_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        masterkey: "{{ .ZITADEL_MASTERKEY }}"
        config-yaml: |
          Database:
            Postgres:
              Host: postgres-rw.database.svc.cluster.local
              Port: 5432
              Database: {{ .ZITADEL_POSTGRES_DB }}
              User:
                Username: {{ .ZITADEL_POSTGRES_USER }}
                Password: {{ .ZITADEL_POSTGRES_PASSWORD }}
                SSL:
                  Mode: disable
              Admin:
                Username: postgres
                Password: {{ .POSTGRES_SUPER_PASS }}
                SSL:
                  Mode: disable
  dataFrom:
    - extract:
        key: zitadel
    - extract:
        key: cloudnative-pg
