---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/kubevirt/macvtap-cni/main/manifests/macvtap.yaml
  - ./configmap.yaml
  - ./networkattachmentdefinition.yaml
