---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cilium
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.19.1
    digest: sha256:22d2bac5b902f5c17ca289466c39c397b5dd5b9074d8e35cd87f632e03832ec4
  url: oci://quay.io/cilium/charts/cilium
