---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name forgejo-runner
spec:
  chartRef:
    kind: OCIRepository
    name: act-runner-scale-set
  interval: 1h
  values:
    giteaConfigUrl: "${FORGEJO_INSTANCE_URL}"
    giteaConfigSecret:
      name: forgejo-runner-secret
    minRunners: 1
    maxRunners: 3
    ephemeral: true
    containerMode:
      type: dind
    securityContext: {}
    persistence:
      enabled: true
      storageClass: openebs-hostpath
      size: 25Gi
    keda:
      enabled: true
      triggerAuthenticationRef: forgejo-runner-controller-trigger-auth
      metricsUrl: "${FORGEJO_INSTANCE_URL}/api/v1/admin/runners/jobs?status=waiting&limit=1"
      pollingInterval: 30
      cooldownPeriod: 300
      scaledJob:
        ttlSecondsAfterFinished: 300
        successfulJobsHistoryLimit: 5
        failedJobsHistoryLimit: 5
    extraEnv:
      - name: NODE
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    extraVolumeMounts:
      - mountPath: /var/run/secrets/talos.dev
        name: talos
        readOnly: true
    extraVolumes:
      - name: talos
        secret:
          secretName: *name
