---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubevirt

components:
  - ../../components/alerts
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./virtualmachines/debian-desktop/app/configmap.yaml
  - ./virtualmachines/debian-server/app/configmap.yaml
  - ./virtualmachines/ubuntu-server/app/configmap.yaml
  - ./virtualmachines/windows-server/app/configmap.yaml
  - ./kubevirt/ks.yaml
  - ./cdi/ks.yaml
  - ./kubevirt-manager/ks.yaml
  - ./virtualmachines/debian-desktop/ks.yaml
  - ./virtualmachines/debian-server/ks.yaml
  - ./virtualmachines/ubuntu-server/ks.yaml
  - ./virtualmachines/windows-server/ks.yaml
