---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: qbittorrent-oidc
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: qbittorrent
  oidc:
    provider:
      issuer: "https://auth.00o.sh/oauth2/openid/qbittorrent"
    clientID: "qbittorrent"
    clientSecret:
      name: qbittorrent-oidc-secret
    redirectURL: "https://qbittorrent.00o.sh/oauth2/callback"
    logoutPath: "/oauth2/sign_out"
