apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-password-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:7JQVW7+r+OO7Cr/wd94XITgRR7yg,iv:mWk0LjKK5i3QiDKvAWC9DVdNUUyw4mq2J2U1ZQ31lXI=,tag:7OkGk57JwS+FVoDFp1oamg==,type:str]
sops:
  age:
    - recipient: age17a9gk8fq0rz9utn3jzhtc2nqvypk996cj5eamuw75j73uphvsursv37973
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0aXNEUVZUb1hYV0EvWTB0
        V05nNEhmY29Ud0VqZTYyVTVKRGtzanlmZkI4CmtFZGZwUTdWZ21iRDdSV255L3FJ
        Q3phVncrZkROZzl2WFkzNFhzMWovb1UKLS0tIHM2VEFvV3RxRXIyVnpVVEdxdko2
        bW9FZDhGZlQ4VlBGeU9ITjhKRmNicEEKQWPDtCKrPdkyRh2ny3ZQfzXlguCo2+Ke
        jk2VX/xmIlcAqPH6ZhLVophAGDVPuBnG2XvgasDznKItl3rzXKvH5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-01T18:45:26Z"
  mac: ENC[AES256_GCM,data:vdycinDxDrR7pn6f2ag060lxLN9sk8HFHcYccgPg2CFTYTjesSuVJQpWpgpVPH6yAqih5oBpvZgplbi/SaWTQihMB5Tr8T/fZ2YWmxwb9567U8NQGjivLHGtR4T67y4kw0GJBlUVX7zGgm2DGBJifhQfew2FOrBl5Hx5G5eHUyQ=,iv:wati0IjnPerzdXh7DtW6TijBvZ9mXjlusQ++NOFMLZw=,tag:F+sfLMd4Yaz43zscuwztBw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
