---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kanidm
spec:
  chartRef:
    kind: OCIRepository
    name: kanidm
  interval: 1h
  values:
    controllers:
      kanidm:
        type: statefulset
        pod:
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            runAsNonRoot: true
            fsGroup: 999
            fsGroupChangePolicy: OnRootMismatch
        containers:
          app:
            image:
              repository: docker.io/kanidm/server
              tag: 1.8.5
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /status
                    port: &port 8443
                    scheme: HTTPS
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

    service:
      app:
        controller: kanidm
        ports:
          https:
            port: 443
            targetPort: *port
          ldaps:
            port: 636
            targetPort: 3636

    route:
      app:
        hostnames:
          - idm.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 443

    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: openebs-hostpath
        advancedMounts:
          kanidm:
            app:
              - path: /data
      config:
        type: configMap
        name: kanidm-configmap
        advancedMounts:
          kanidm:
            app:
              - path: /data/server.toml
                subPath: server.toml
      certs:
        type: secret
        name: kanidm-tls
        defaultMode: 0400
        advancedMounts:
          kanidm:
            app:
              - path: /certs
      run:
        type: emptyDir
        advancedMounts:
          kanidm:
            app:
              - path: /var/run
