---
apiVersion: kaniop.rs/v1beta1
kind: Kanidm
metadata:
  name: kanidm
spec:
  # renovate: datasource=docker depName=docker.io/kanidm/server
  image: docker.io/kanidm/server:1.8.5
  domain: auth.${SECRET_DOMAIN}
  replicaGroups:
    - name: default
      replicas: 1
      resources:
        requests:
          cpu: 10m
          memory: 128Mi
        limits:
          memory: 512Mi
  tlsSecretName: kanidm-tls
  ldapPortName: ldaps
  env:
    - name: KANIDM_TRUST_X_FORWARD_FOR
      value: "true"
  storage:
    emptyDir: {}
  volumeMounts:
    - name: data
      mountPath: /data
  securityContext:
    runAsUser: 999
    runAsGroup: 999
    fsGroup: 999
    fsGroupChangePolicy: OnRootMismatch
  containers:
    - name: tools
      image: docker.io/kanidm/tools:1.8.5
      command: ["sleep", "infinity"]
      env:
        - name: KANIDM_URL
          value: https://localhost:8443
        - name: KANIDM_ACCEPT_INVALID_CERTS
          value: "true"
      resources:
        requests:
          cpu: 1m
          memory: 16Mi
        limits:
          memory: 64Mi
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: ["ALL"]
      volumeMounts:
        - name: tools-cache
          mountPath: /.cache
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: kanidm
    - name: tools-cache
      emptyDir: {}
