---
apiVersion: kaniop.rs/v1beta1
kind: Kanidm
metadata:
  name: kanidm
spec:
  # renovate: datasource=docker depName=docker.io/kanidm/server
  image: docker.io/kanidm/server:1.11.1@sha256:7c3d7ed868e91f78c24a7fb9c548876563b375a4203021b730d58369b97ad154
  domain: auth.${SECRET_DOMAIN}
  replicaGroups:
    - name: default
      replicas: 1
      resources:
        requests:
          cpu: 10m
          memory: 128Mi
        limits:
          memory: 512Mi
  tlsSecretName: kanidm-tls
  ldapPortName: ldaps
  env:
    - name: KANIDM_TRUST_X_FORWARD_FOR
      value: "true"
    - name: KANIDM_ONLINE_BACKUP_PATH
      value: /data/backups/
    - name: KANIDM_ONLINE_BACKUP_SCHEDULE
      value: "00 02 * * *"
    - name: KANIDM_ONLINE_BACKUP_VERSIONS
      value: "7"
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: openebs-hostpath
  securityContext:
    runAsUser: 999
    runAsGroup: 999
    fsGroup: 999
    fsGroupChangePolicy: OnRootMismatch
