---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: opencost
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 2.5.8
    digest: sha256:8ed99964cc47c6068021100c4ca7ad15efb1aecaff5e4a3984d331ffa7114723
  url: oci://ghcr.io/opencost/charts/opencost
