---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: kubevirt-manager
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: kubevirt-manager-app
  connection:
    bufferLimit: 32Mi
  tcpKeepalive:
    probes: 3
    idleTime: 60s
    interval: 60s
  timeout:
    http:
      requestTimeout: 0s
      idleTimeout: 0s
