---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: opencost
spec:
  dependsOn:
    - name: kube-prometheus-stack
    - name: kanidm-config
      namespace: identity
    - name: onepassword
      namespace: external-secrets
  interval: 1h
  path: ./kubernetes/apps/observability/opencost/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: observability
  wait: false
