---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: gatus-secret
    template:
      data:
        BUDDY_DISCORD_WEBHOOK_URL: "{{ .BUDDY_DISCORD_WEBHOOK_URL }}"
        BUDDY_HEARTBEAT_TOKEN: "{{ .BUDDY_HEARTBEAT_TOKEN }}"
        BUDDY_STATUS_HOSTNAME: "{{ .BUDDY_STATUS_HOSTNAME }}"
  dataFrom:
    - extract:
        key: gatus
