---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: n8n-secret
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: "{{ .N8N_POSTGRES_DB }}"
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_PORT: "5432"
        INIT_POSTGRES_USER: "{{ .N8N_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .N8N_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        N8N_ENCRYPTION_KEY: "{{ .N8N_ENCRYPTION_KEY }}"
  dataFrom:
    - extract:
        key: n8n
    - extract:
        key: cloudnative-pg
