---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./clustersecretstore.yaml
  - ./clustersecretstore-sdk.yaml
  - ./clustersecretstore-kubernetes.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
  - ./secret.sops.yaml
  - ./secret-connect.sops.yaml