---
apiVersion: v1
kind: ConfigMap
metadata:
  name: b2-k3s01-vars
data:
  VM_NAME: b2-k3s01
  VM_IP: 192.168.57.15
  VM_MAC: "52:54:00:57:00:15"
  VM_CPU: "2"
  VM_MEMORY: 4G
  VM_STORAGE: 50Gi
  VM_GATEWAY: 192.168.57.1
  VM_DNS: 192.168.57.1
  VM_NETWORK: network/vm-macvtap
  VM_IMAGE: "docker://quay.io/containerdisks/debian:12"
