---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubevirt
spec:
  chartRef:
    kind: OCIRepository
    name: kubevirt
  interval: 1h
  values:
    kubevirt:
      configuration:
        developerConfiguration:
          featureGates:
            - LiveMigration
            - Macvtap
            - HotplugVolumes
            - HostDevices
            - GPU
        network:
          permitBridgeInterfaceOnPodNetwork: true
