---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-secret
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: "{{ .FORGEJO_POSTGRES_DB }}"
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_PORT: "5432"
        INIT_POSTGRES_USER: "{{ .FORGEJO_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .FORGEJO_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_DB: "{{ .FORGEJO_POSTGRES_DB }}"
        POSTGRES_USERNAME: "{{ .FORGEJO_POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ .FORGEJO_POSTGRES_PASSWORD }}"
        FORGEJO_SECRET_KEY: "{{ .FORGEJO_SECRET_KEY }}"
        FORGEJO_INTERNAL_TOKEN: "{{ .FORGEJO_INTERNAL_TOKEN }}"
        username: "{{ .FORGEJO_ADMIN_USERNAME }}"
        password: "{{ .FORGEJO_ADMIN_PASSWORD }}"
        email: "{{ .FORGEJO_ADMIN_EMAIL }}"
        key: "{{ .FORGEJO_OIDC_CLIENT_ID }}"
        secret: "{{ .FORGEJO_OIDC_CLIENT_SECRET }}"
  data:
    - secretKey: FORGEJO_OIDC_CLIENT_ID
      sourceRef:
        storeRef:
          name: kubernetes-identity
          kind: ClusterSecretStore
      remoteRef:
        key: forgejo-kanidm-oauth2-credentials
        property: CLIENT_ID
    - secretKey: FORGEJO_OIDC_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: kubernetes-identity
          kind: ClusterSecretStore
      remoteRef:
        key: forgejo-kanidm-oauth2-credentials
        property: CLIENT_SECRET
  dataFrom:
    - extract:
        key: forgejo
    - extract:
        key: cloudnative-pg
