---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
spec:
  chartRef:
    kind: OCIRepository
    name: forgejo
  interval: 1h
  values:
    controllers:
      forgejo:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18@sha256:3c54d39f19fdb82ed5b3f286450e4071133cc6025bd0e25856bc2c522f8fc030
            envFrom:
              - secretRef:
                  name: forgejo-secret
          init-config:
            dependsOn: init-db
            image:
              repository: codeberg.org/forgejo/forgejo
              tag: 14.0.2-rootless
            command: ["/bin/sh", "-c"]
            args:
              - |
                mkdir -p /data/gitea/conf
                cp /etc/forgejo/app.ini /data/gitea/conf/app.ini
        containers:
          app:
            image:
              repository: codeberg.org/forgejo/forgejo
              tag: 14.0.2-rootless
            env:
              FORGEJO__database__DB_TYPE: postgres
            envFrom:
              - secretRef:
                  name: forgejo-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/healthz
                    port: &port 3000
                  initialDelaySeconds: 15
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: forgejo
        ports:
          http:
            port: *port
      ssh:
        type: LoadBalancer
        controller: forgejo
        annotations:
          external-dns.alpha.kubernetes.io/hostname: git.00o.sh
          lbipam.cilium.io/ips: 10.0.6.20
        externalTrafficPolicy: Cluster
        ports:
          ssh:
            port: &sshPort 22
            targetPort: 2222
    route:
      app:
        hostnames:
          - git.00o.sh
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port
      external:
        hostnames:
          - git.00o.sh
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    configMaps:
      config:
        data:
          app.ini: |-
            [server]
            DOMAIN = git.00o.sh
            ROOT_URL = https://git.00o.sh
            HTTP_PORT = 3000
            SSH_DOMAIN = git.00o.sh
            SSH_PORT = 22
            SSH_LISTEN_PORT = 2222
            LFS_START_SERVER = true
            INSTALL_LOCK = true

            [service]
            DISABLE_REGISTRATION = false
            REQUIRE_SIGNIN_VIEW = false

            [openid]
            ENABLE_OPENID_SIGNIN = true

            [oauth2_client]
            ENABLE_AUTO_REGISTRATION = true
            OPENID_CONNECT_SCOPES = openid email profile
            USERNAME = preferred_username

            [mailer]
            ENABLED = true
            PROTOCOL = smtp
            SMTP_ADDR = smtp-relay.utils.svc.cluster.local
            SMTP_PORT = 25
            FROM = forgejo@00o.sh
    persistence:
      data:
        existingClaim: forgejo
        globalMounts:
          - path: /data
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
      config-file:
        type: configMap
        identifier: config
        advancedMounts:
          forgejo:
            init-config:
              - path: /etc/forgejo/app.ini
                subPath: app.ini
                readOnly: true
