---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kaniop
spec:
  interval: 1h
  path: ./kubernetes/apps/identity/kanidm/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: identity
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kanidm
spec:
  dependsOn:
    - name: kaniop
    - name: cert-manager
      namespace: cert-manager
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: Certificate
      name: kanidm-tls
      namespace: identity
  interval: 1h
  path: ./kubernetes/apps/identity/kanidm/instance
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: identity
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kanidm-config
spec:
  dependsOn:
    - name: kanidm
    - name: onepassword
      namespace: external-secrets
  interval: 1h
  path: ./kubernetes/apps/identity/kanidm/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: identity
  wait: false
