apiVersion: v1
kind: Secret
metadata:
  name: qui-secret
stringData:
  QUI__SESSION_SECRET: ENC[AES256_GCM,data:SeLCYhx95kiIsg9k,iv:R6KmYLoAEbAuqq/Z+qWUY76ozRneLzgZIR9d4k7VLMs=,tag:Qj6vbK5TwSut2mrOZXJQ1A==,type:str]
sops:
  age:
    - recipient: age17a9gk8fq0rz9utn3jzhtc2nqvypk996cj5eamuw75j73uphvsursv37973
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0c3RGMXEyZ3Z3emd5cGMr
        YTVzY0Mxb2o1enlnRXQySXVZVnVPQzJ3YjFRCmppOEcxbjNKbk1EOG4xdjNKQUpo
        K3VZVEsrSDVUdmVPTE9GejA4Zm5FaUEKLS0tIFNQNFRReW1aOGp5SCtmZWMyc0RG
        RXF6VGwvN2JnVVF4azJ4R3VxODNpeTQKphtqlvsHrgNv6jUuCPIK2NhDEdb87mXD
        MCw5Ex7fdma5OBLx9YJo1O4BheTGFjIBI9GX1W4pY1qU6FQyuRca0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T22:47:52Z"
  mac: ENC[AES256_GCM,data:vZOSEQnw/Wts5IZkr2C0t2fU/T6DC0uRFnnLBh8gSh+bxb9xw9PFFljKW8jH+oRL1JnXqwfHonkKMomfYD5Kxr7t3MkTWA0O7Y4VmF2cHuhCxK8kKQGnBRegR51m5nPa6YY1cQ85a8drQPnFVrqbKWxYs8a7R+k049y6iJcaJQY=,iv:SdeHjEa+ewfnshra71xrq9qHYKFC4UD3iTcqMbmiOsU=,tag:p+oGtSIEm0oyoJQvGqkwlQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
