---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: qui-oidc
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: qui
  oidc:
    provider:
      issuer: "https://auth.00o.sh/oauth2/openid/qui"
    clientID: "qui"
    clientSecret:
      name: qui-oidc-secret
    redirectURL: "https://qui.00o.sh/oauth2/callback"
    logoutPath: "/oauth2/sign_out"
