---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ubuntu-server
spec:
  dependsOn:
    - name: kubevirt
    - name: cdi
    - name: macvtap-cni
      namespace: network
  interval: 1h
  path: ./kubernetes/apps/kubevirt/ubuntu-server/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kubevirt
  wait: false
