---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kguardian
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kguardian-secret
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgres://{{ .KGUARDIAN_POSTGRES_USER }}:{{ .KGUARDIAN_POSTGRES_PASSWORD }}@postgres-rw.database.svc.cluster.local:5432/{{ .KGUARDIAN_POSTGRES_DB }}"
        INIT_POSTGRES_DBNAME: "{{ .KGUARDIAN_POSTGRES_DB }}"
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_PORT: "5432"
        INIT_POSTGRES_USER: "{{ .KGUARDIAN_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .KGUARDIAN_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: kguardian
    - extract:
        key: cloudnative-pg
