---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kguardian
spec:
  chartRef:
    kind: OCIRepository
    name: kguardian
  interval: 1h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    broker:
      image:
        repository: ghcr.io/kguardian-dev/kguardian/broker
        tag: v1.7.1@sha256:127de1eef64fe6de7d58d9c79a517097939b9c948c1f2bb74703008acbb080a9
    controller:
      image:
        repository: ghcr.io/kguardian-dev/kguardian/controller
        tag: v1.8.1
      initContainer:
        image:
          repository: busybox
          tag: stable@sha256:b9598f8c98e24d0ad42c1742c32516772c3aa2151011ebaf639089bd18c605b8
      excludedNamespaces:
        - kube-system
    database:
      image:
        repository: postgres
        tag: 18-alpine@sha256:4da1a4828be12604092fa55311276f08f9224a74a62dcb4708bd7439e2a03911
    frontend:
      image:
        repository: ghcr.io/kguardian-dev/kguardian/frontend
        tag: v1.8.0@sha256:e063abd48ba1438130c1f55e3e25c181d689484a14b4d923f964847c68c3d7e3
    llmBridge:
      enabled: false
    mcpServer:
      enabled: false
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: kguardian-broker
            patch: |
              - op: replace
                path: /spec/template/spec/containers/0/env
                value:
                  - name: DATABASE_URL
                    valueFrom:
                      secretKeyRef:
                        name: kguardian-secret
                        key: DATABASE_URL
              - op: add
                path: /spec/template/spec/initContainers
                value:
                  - name: init-db
                    image: ghcr.io/home-operations/postgres-init:18@sha256:6fa1f331cddd2eb0b6afa7b8d3685c864127a81ab01c3d9400bc3ff5263a51cf
                    envFrom:
                      - secretRef:
                          name: kguardian-secret
          - target:
              kind: DaemonSet
              name: kguardian-controller
            patch: |
              apiVersion: apps/v1
              kind: DaemonSet
              metadata:
                name: kguardian-controller
              spec:
                template:
                  spec:
                    containers:
                      - name: controller
                        env:
                          - name: RUST_LOG
                            value: "kguardian::pod_reconciler=debug,kguardian=info"
          - target:
              kind: Deployment
              name: kguardian-database
            patch: |
              - op: replace
                path: /spec/replicas
                value: 0
