---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kguardian
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.8.2@sha256:055e85e3447e56eefd306edf2c4294ad80a3b3d42560e56c6927be82ea6db330
  url: oci://ghcr.io/kguardian-dev/charts/kguardian
