---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.0.6.10:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.0.6.10"
additionalMachineCertSans: *sans

clusterPodNets: ["172.30.0.0/16"]
clusterSvcNets: ["172.31.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "singlenodemaster"
    ipAddress: "10.0.6.211"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/1f27123b6d8a11ff4f1b5f09f839f3662244f6bb11124faebe050c632291947b
    controlPlane: true

    networkInterfaces:
      - interface: bond0
        bond:
          mode: active-backup
          deviceSelectors: [{ hardwareAddr: "58:47:ca:74:e4:*", driver: igc }]
        mtu: 1500
        dhcp: false
        addresses:
          - 10.0.6.211/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.6.1
        vip:
          ip: 10.0.6.10

  # Control plane nodes running as Proxmox VE VMs
  - hostname: "node-01-pve"
    ipAddress: "10.0.6.212"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/10f9392d7091b30abf573524649756e5bc894f653af525836e9ab0297f301fc2
    controlPlane: true
    networkInterfaces:
      - interface: bond0
        bond:
          mode: active-backup
          deviceSelectors: [{ hardwareAddr: "bc:24:11:d7:17:*" }]
        mtu: 1500
        dhcp: false
        addresses:
          - 10.0.6.212/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.6.1
        vip:
          ip: 10.0.6.10
    patches:
      - "@./patches/vm-node/machine-kubelet.yaml"

  - hostname: "node-02-pve"
    ipAddress: "10.0.6.213"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/10f9392d7091b30abf573524649756e5bc894f653af525836e9ab0297f301fc2
    controlPlane: true
    networkInterfaces:
      - interface: bond0
        bond:
          mode: active-backup
          deviceSelectors: [{ hardwareAddr: "bc:24:11:80:3e:*" }]
        mtu: 1500
        dhcp: false
        addresses:
          - 10.0.6.213/24
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.6.1
        vip:
          ip: 10.0.6.10
    patches:
      - "@./patches/vm-node/machine-kubelet.yaml"


# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-kubevirt.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/machine-vlan56.yaml"
  - "@./patches/global/machine-vlan57.yaml"


# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"
