---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ui-bakery-db
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ui-bakery-db-secret
    template:
      data:
        password: "{{ .UI_BAKERY_DB_PASSWORD }}"
  dataFrom:
    - extract:
        key: uibakery
