---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ubuntu-server-vars
data:
  VM_NAME: ubuntu-server
  VM_IP: 192.168.57.10
  VM_MAC: "52:54:00:57:00:10"
  VM_CPU: "1"
  VM_MEMORY: 1G
  VM_STORAGE: 30Gi
  VM_GATEWAY: 192.168.57.1
  VM_DNS: 192.168.57.1
  VM_NETWORK: network/vm-macvtap
  VM_IMAGE: "docker://quay.io/containerdisks/ubuntu:26.04"
