---
apiVersion: v1
kind: ConfigMap
metadata:
  name: debian-desktop-vars
data:
  VM_NAME: debian-desktop
  VM_IP: 192.168.57.12
  VM_MAC: "52:54:00:57:00:12"
  VM_STORAGE: 50Gi
  VM_IMAGE: "docker://quay.io/containerdisks/debian:13"
