---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: ${VM_NAME}
spec:
  endpoints:
    - dnsName: ${VM_NAME}.00o.sh
      recordTTL: 300
      recordType: A
      targets:
        - ${VM_IP}
