---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freepbx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: freepbx-secret
    template:
      data:
        DB_PASS: "{{ .FREEPBX_DB_PASSWORD }}"
  dataFrom:
    - extract:
        key: freepbx
