---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: freepbx-b1-asterisk
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: b1_asterisk
  table: "*"
  username: freepbx
  host: "%"
  grantOption: false
  cleanupPolicy: Skip
  requeueInterval: 30s
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: freepbx-b1-asteriskcdrdb
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: b1_asteriskcdrdb
  table: "*"
  username: freepbx
  host: "%"
  grantOption: false
  cleanupPolicy: Skip
  requeueInterval: 30s
  retryInterval: 5s
