---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dbgate
spec:
  suspend: ${CLUSTER_TIER2_SUSPENDED}
  dependsOn:
    - name: cloudnative-pg
    - name: mariadb-operator
    - name: kanidm-config
      namespace: identity
    - name: onepassword
      namespace: external-secrets
  interval: 1h
  path: ./kubernetes/apps/database/dbgate/app
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: database
  wait: false
