---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freepbx-b2-k3s01-db
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: freepbx-b2-k3s01-db-secret
    template:
      data:
        password: "{{ .FREEPBX_DB_PASSWORD }}"
  dataFrom:
    - extract:
        key: freepbx
