---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ${VM_NAME}
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: ${VM_NAME}
      annotations:
        kubevirt.io/allow-pod-bridge-network-live-migration: "true"
        k8s.v1.cni.cncf.io/networks: |-
          [{
            "name": "vm-macvtap",
            "namespace": "network",
            "mac": "${VM_MAC}"
          }]
    spec:
      evictionStrategy: LiveMigrate
      domain:
        cpu:
          cores: ${VM_CPU}
        resources:
          requests:
            memory: ${VM_MEMORY}
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: lan
              binding:
                name: macvtap
      networks:
        - name: lan
          multus:
            networkName: ${VM_NETWORK}
      volumes:
        - name: rootdisk
          dataVolume:
            name: ${VM_NAME}-pvc
        - name: cloudinitdisk
          cloudInitNoCloud:
            networkData: |
              network:
                version: 1
                config:
                  - type: physical
                    name: enp1s0
                    subnets:
                      - type: static
                        address: ${VM_IP}/24
                        gateway: ${VM_GATEWAY}
                        dns_nameservers:
                          - ${VM_DNS}
            secretRef:
              name: ${VM_NAME}-cloudinit
  dataVolumeTemplates:
    - metadata:
        name: ${VM_NAME}-pvc
      spec:
        storage:
          resources:
            requests:
              storage: ${VM_STORAGE}
          accessModes:
            - ReadWriteMany
          storageClassName: nfs-fast
        source:
          registry:
            url: "${VM_IMAGE}"
