---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freepbx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: freepbx-secret
    template:
      data:
        FPBX_CF_TUNNEL_TOKEN: "{{ .FPBX_CF_TUNNEL_TOKEN }}"
  dataFrom:
    - extract:
        key: freepbx
