---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ui-bakery
spec:
  refreshInterval: 8h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ui-bakery-secret
    template:
      engineVersion: v2
      data:
        UI_BAKERY_LICENSE_KEY: "{{ .UI_BAKERY_LICENSE_KEY }}"
        UI_BAKERY_JWT_SECRET: "{{ .UI_BAKERY_JWT_SECRET }}"
        UI_BAKERY_JWT_REFRESH_SECRET: "{{ .UI_BAKERY_JWT_REFRESH_SECRET }}"
        UI_BAKERY_JWT_SERVICE_ACCOUNT_SECRET: "{{ .UI_BAKERY_JWT_SERVICE_ACCOUNT_SECRET }}"
        UI_BAKERY_CREDENTIALS_SECRET: "{{ .UI_BAKERY_CREDENTIALS_SECRET }}"
        UI_BAKERY_MFA_SECRET: "{{ .UI_BAKERY_MFA_SECRET }}"
        UI_BAKERY_DB_PASSWORD: "{{ .UI_BAKERY_DB_PASSWORD }}"
  dataFrom:
    - extract:
        key: uibakery
