---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ui-bakery
spec:
  chartRef:
    kind: OCIRepository
    name: ui-bakery
  interval: 1h
  values:
    controllers:
      gateway:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: cruibakeryonprem.azurecr.io/cloud/gateway
              tag: latest
            env:
              UI_BAKERY_APP_SERVER_NAME: https://uibakery.00o.sh
              UI_BAKERY_DB_HOST: mariadb-primary.database.svc.cluster.local
              UI_BAKERY_DB_PORT: "3306"
              UI_BAKERY_DB_DATABASE: bakery
              UI_BAKERY_DB_USERNAME: bakery
              UI_BAKERY_INTERNAL_API_URL: http://bakery-back:8080
              UI_BAKERY_INTERNAL_DATABASE_ENABLED: "false"
            envFrom:
              - secretRef:
                  name: ui-bakery-secret
            probes:
              liveness: &gatewayProbes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &gatewayPort 3030
                  initialDelaySeconds: 5
                  periodSeconds: 30
              readiness: *gatewayProbes
            resources:
              requests:
                cpu: 125m
                memory: 128Mi
              limits:
                memory: 256Mi

      backend:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: cruibakeryonprem.azurecr.io/cloud/bakery-back
              tag: latest
            env:
              UI_BAKERY_APP_SERVER_NAME: https://uibakery.00o.sh
              UI_BAKERY_DB_HOST: mariadb-primary.database.svc.cluster.local
              UI_BAKERY_DB_PORT: "3306"
              UI_BAKERY_DB_DATABASE: bakery
              UI_BAKERY_DB_USERNAME: bakery
              UI_BAKERY_INTERNAL_API_URL: http://bakery-back:8080
              UI_BAKERY_INTERNAL_DATABASE_ENABLED: "false"
            envFrom:
              - secretRef:
                  name: ui-bakery-secret
            probes:
              liveness: &backendProbes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /status
                    port: &backendPort 8080
                  initialDelaySeconds: 15
                  periodSeconds: 30
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /status
                    port: *backendPort
                  failureThreshold: 100
                  periodSeconds: 3
              readiness: *backendProbes
            resources:
              requests:
                cpu: 500m
                memory: 1024Mi
              limits:
                memory: 2048Mi

      automation:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: cruibakeryonprem.azurecr.io/cloud/automation
              tag: latest
            env:
              UI_BAKERY_APP_SERVER_NAME: https://uibakery.00o.sh
              UI_BAKERY_DB_HOST: mariadb-primary.database.svc.cluster.local
              UI_BAKERY_DB_PORT: "3306"
              UI_BAKERY_DB_DATABASE: bakery
              UI_BAKERY_DB_USERNAME: bakery
              UI_BAKERY_INTERNAL_API_URL: http://bakery-back:8080
              UI_BAKERY_INTERNAL_DATABASE_ENABLED: "false"
            envFrom:
              - secretRef:
                  name: ui-bakery-secret
            probes:
              liveness: &automationProbes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /status
                    port: &automationPort 4000
                  initialDelaySeconds: 15
                  periodSeconds: 30
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /status
                    port: *automationPort
                  failureThreshold: 30
                  periodSeconds: 3
              readiness: *automationProbes
            resources:
              requests:
                cpu: 500m
                memory: 512Mi
              limits:
                memory: 1024Mi

      bakery-front:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: cruibakeryonprem.azurecr.io/cloud/bakery-front
              tag: latest
            env:
              UI_BAKERY_APP_SERVER_NAME: https://uibakery.00o.sh
              UI_BAKERY_DB_HOST: mariadb-primary.database.svc.cluster.local
              UI_BAKERY_DB_PORT: "3306"
              UI_BAKERY_DB_DATABASE: bakery
              UI_BAKERY_DB_USERNAME: bakery
              UI_BAKERY_INTERNAL_API_URL: http://bakery-back:8080
              UI_BAKERY_INTERNAL_DATABASE_ENABLED: "false"
            envFrom:
              - secretRef:
                  name: ui-bakery-secret
            probes:
              liveness: &bakeryFrontProbes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &bakeryFrontPort 8080
                  initialDelaySeconds: 5
                  periodSeconds: 30
              readiness: *bakeryFrontProbes
            resources:
              requests:
                cpu: 125m
                memory: 128Mi
              limits:
                memory: 256Mi

      datasource:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: cruibakeryonprem.azurecr.io/cloud/datasource
              tag: latest
            env:
              UI_BAKERY_APP_SERVER_NAME: https://uibakery.00o.sh
              UI_BAKERY_DB_HOST: mariadb-primary.database.svc.cluster.local
              UI_BAKERY_DB_PORT: "3306"
              UI_BAKERY_DB_DATABASE: bakery
              UI_BAKERY_DB_USERNAME: bakery
              UI_BAKERY_INTERNAL_API_URL: http://bakery-back:8080
              UI_BAKERY_INTERNAL_DATABASE_ENABLED: "false"
            envFrom:
              - secretRef:
                  name: ui-bakery-secret
            probes:
              liveness: &datasourceProbes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /status
                    port: &datasourcePort 6060
                  initialDelaySeconds: 15
                  periodSeconds: 30
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /status
                    port: *datasourcePort
                  failureThreshold: 30
                  periodSeconds: 3
              readiness: *datasourceProbes
            resources:
              requests:
                cpu: 500m
                memory: 512Mi
              limits:
                memory: 1024Mi

      python-runtime:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: cruibakeryonprem.azurecr.io/cloud/python-runtime
              tag: latest
            env:
              UI_BAKERY_APP_SERVER_NAME: https://uibakery.00o.sh
              UI_BAKERY_DB_HOST: mariadb-primary.database.svc.cluster.local
              UI_BAKERY_DB_PORT: "3306"
              UI_BAKERY_DB_DATABASE: bakery
              UI_BAKERY_DB_USERNAME: bakery
              UI_BAKERY_INTERNAL_API_URL: http://bakery-back:8080
              UI_BAKERY_INTERNAL_DATABASE_ENABLED: "false"
            envFrom:
              - secretRef:
                  name: ui-bakery-secret
            probes:
              liveness: &pythonProbes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &pythonPort 5050
                  initialDelaySeconds: 5
                  periodSeconds: 30
              readiness: *pythonProbes
            resources:
              requests:
                cpu: 250m
                memory: 256Mi
              limits:
                memory: 512Mi

      workbench-front:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: cruibakeryonprem.azurecr.io/cloud/workbench-front
              tag: latest
            env:
              UI_BAKERY_APP_SERVER_NAME: https://uibakery.00o.sh
              UI_BAKERY_DB_HOST: mariadb-primary.database.svc.cluster.local
              UI_BAKERY_DB_PORT: "3306"
              UI_BAKERY_DB_DATABASE: bakery
              UI_BAKERY_DB_USERNAME: bakery
              UI_BAKERY_INTERNAL_API_URL: http://bakery-back:8080
              UI_BAKERY_INTERNAL_DATABASE_ENABLED: "false"
            envFrom:
              - secretRef:
                  name: ui-bakery-secret
            probes:
              liveness: &workbenchProbes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &workbenchPort 8080
                  initialDelaySeconds: 5
                  periodSeconds: 30
              readiness: *workbenchProbes
            resources:
              requests:
                cpu: 120m
                memory: 128Mi
              limits:
                memory: 256Mi

    service:
      gateway:
        controller: gateway
        ports:
          http:
            port: *gatewayPort
      backend:
        controller: backend
        ports:
          http:
            port: *backendPort
      automation:
        controller: automation
        ports:
          http:
            port: *automationPort
      bakery-front:
        controller: bakery-front
        ports:
          http:
            port: *bakeryFrontPort
      datasource:
        controller: datasource
        ports:
          http:
            port: *datasourcePort
      python-runtime:
        controller: python-runtime
        ports:
          http:
            port: *pythonPort
      workbench-front:
        controller: workbench-front
        ports:
          http:
            port: *workbenchPort

    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Utilities
          gethomepage.dev/name: UI Bakery
          gethomepage.dev/icon: https://uibakery.io/img/favicon.ico
          gethomepage.dev/description: Low-Code Internal Tool Builder
          gethomepage.dev/href: "https://uibakery.00o.sh"
        hostnames:
          - uibakery.00o.sh
        parentRefs:
          - name: envoy-external
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: gateway
                port: *gatewayPort
