---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ${VM_NAME}
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: ${VM_NAME}
      annotations:
        kubevirt.io/allow-pod-bridge-network-live-migration: "true"
        k8s.v1.cni.cncf.io/networks: |-
          [{
            "name": "vm-macvtap",
            "namespace": "network",
            "mac": "${VM_MAC}"
          }]
    spec:
      evictionStrategy: LiveMigrate
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 2G
        features:
          acpi: {}
          apic: {}
        firmware:
          bootloader:
            efi:
              secureBoot: false
        devices:
          disks:
            - name: rootdisk
              bootOrder: 1
              disk:
                bus: sata
            - name: installiso
              bootOrder: 69
              cdrom:
                bus: sata
            - name: virtio-drivers
              cdrom:
                bus: sata
          interfaces:
            - name: lan
              binding:
                name: macvtap
      networks:
        - name: lan
          multus:
            networkName: network/vm-macvtap
      volumes:
        - name: rootdisk
          dataVolume:
            name: ${VM_NAME}-pvc
        - name: installiso
          containerDisk:
            image: ${VM_IMAGE}
        - name: virtio-drivers
          containerDisk:
            image: ${VM_DRIVERS_IMAGE}
  dataVolumeTemplates:
    - metadata:
        name: ${VM_NAME}-pvc
      spec:
        storage:
          resources:
            requests:
              storage: ${VM_STORAGE}
          accessModes:
            - ReadWriteMany
          storageClassName: nfs-fast
        source:
          blank: {}
