---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: windows-server
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: windows-server
      annotations:
        kubevirt.io/allow-pod-bridge-network-live-migration: "true"
        k8s.v1.cni.cncf.io/networks: |-
          [{
            "name": "vm-macvtap",
            "namespace": "network",
            "mac": "52:54:00:57:00:20"
          }]
    spec:
      evictionStrategy: LiveMigrate
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 2G
        features:
          acpi: {}
          apic: {}
        firmware:
          bootloader:
            efi:
              secureBoot: false
        devices:
          disks:
            - name: rootdisk
              bootOrder: 2
              disk:
                bus: sata
            - name: installiso
              bootOrder: 1
              cdrom:
                bus: sata
            - name: virtio-drivers
              cdrom:
                bus: sata
          interfaces:
            - name: lan
              binding:
                name: macvtap
      networks:
        - name: lan
          multus:
            networkName: network/vm-macvtap
      volumes:
        - name: rootdisk
          dataVolume:
            name: windows-server-pvc
        - name: installiso
          containerDisk:
            # renovate: datasource=docker depName=ghcr.io/00o-sh/windows-server
            image: ghcr.io/00o-sh/windows-server:ltsc2022-eval-np@sha256:190364def1b3c58bbce8073e5fcd1de0affaf8d94ba379e5e64dca3a2f6c1b19
        - name: virtio-drivers
          containerDisk:
            # renovate: datasource=docker depName=ghcr.io/00o-sh/windows-drivers
            image: ghcr.io/00o-sh/windows-drivers:ltsc2022-eval@sha256:b120988d578533232f623724db876621434100be5065089f93a9219b0038b543
  dataVolumeTemplates:
    - metadata:
        name: windows-server-pvc
      spec:
        storage:
          resources:
            requests:
              storage: 60Gi
          accessModes:
            - ReadWriteMany
          storageClassName: nfs-fast
        source:
          blank: {}
